### ISSUE TITLE
[Question] Include own VCF files

### ISSUE THREAD

**Issue by ypriverol** [nf-core/pgdb#7]
## Additional context

This issue is from @jgriss,

Short question: Is it also possible to directly create a FASTA file based on your own VCF files using this pipeline?

Thanks a lot!

Johannes

**Comment by husensofteng** [comment]
added a new process to support own vcf
@ypriverol need to test commit: 7ddf11bc34019e32095f686e1af34d288eb4265f after deploying the new version of [pypgatk](https://github.com/bigbio/py-pgatk/tree/dev)

**Comment by jgriss** [comment]
Hi @husensofteng 

Thanks a lot! How can I launch this process?

Unfortunately, I failed to figure out how to display the help section.

**Comment by husensofteng** [comment]
Hi @jgriss,

The command to translate own vcf would be (pull the latest changes):
`nextflow run main.nf -profile conda --ensembl_name homo_sapiens -resume --vcf true --vcf_file input_file.vcf`

note: it assumes that your variants are mapped to hg38 because it uses the latest assembly from ENSEMBL to annotate and translate the variants within CDS.

**Comment by jgriss** [comment]
Hi @husensofteng,

Thanks a lot! I'll give it a try right away.

Kind regards,
Johannes

**Comment by husensofteng** [comment]
I assume the issue is solved, please feel free to re-open if you get any error.
